ur10:
  controller_manager:
    ros__parameters:
      update_rate: 100 # Hz
      use_sim_time: true
      ur10_arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      ur10_gripper_controller:
        type: position_controllers/GripperActionController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  ur10_gripper_controller:
    ros__parameters:
      use_sim_time: true
      joint: finger_joint

  ur10_arm_controller:
    ros__parameters:
      use_sim_time: true

      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint
      allow_nonzero_velocity_at_trajectory_end: true
