planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  joint_state_topic: "/ur10/joint_states"
  attached_collision_object_topic: "/ur10/planning_scene_monitor"
  publish_planning_scene_topic: "/ur10/publish_planning_scene"
  monitored_planning_scene_topic: "/ur10/monitored_planning_scene"
  wait_for_initial_state_timeout: 10.0

planning_pipelines:
  pipeline_names: ["ompl", "chomp"]

plan_request_params:
  planning_attempts: 10
  planning_pipeline: ompl
  planner_id: "RRTConnectkConfigDefault"
  max_velocity_scaling_factor: 0.5
  max_acceleration_scaling_factor: 0.5
  planning_time: 10.0

ompl_rrtc:
  plan_request_params:
    planning_attempts: 10
    planning_pipeline: ompl
    planner_id: "RRTConnectkConfigDefault"
    max_velocity_scaling_factor: 0.5
    max_acceleration_scaling_factor: 0.5
    planning_time: 5.0

chomp_planner:
  plan_request_params:
    planning_attempts: 10
    planning_pipeline: chomp
    max_velocity_scaling_factor: 0.5
    max_acceleration_scaling_factor: 0.5
    planning_time: 5.0
