prepare_data:
  # Topics
  pointcloud_topic: pointcloud_topic

  # Data folder
  images_folder: images

  # Runtime variables
  image_scale: 0.04
  set_frames: false
  frames_to_process: 1
  preprocess_all_data: true
  fake_orientation: true
  list_json_files: false

send_data:
  playback_rate: 1
  bag_name:

scenario_replayer:
  gazebo_teleport_service: /world/default/set_pose
  frame_id: real_data
  use_cmd_vel: false
  ignore_orientation: false

shared:
  frame_id: real_data
  namespace: visualize_real_data
  entity_topic: entity_topic
  #json_file_name has to be set to an existing file in replay_data folder
  json_file_name: example_trajectory.json
  start_time: ""
  end_time: ""
  initial_heading: 0.0  # Initial heading/orientation in degrees (0 = pointing left). Positive heading is counter-clockwise, i.e. 90 deg = DOWN. Used by orientation_faker.py

  # Can be changed to move the frame
  frame_position:
    x: 15.35
    y: 5.7
    z: -0.2

  # Calculated during preparation
  extracted_fps: 10.0

  # Could be increased for greater overhead,
  # or reduced for greater processing speed (risky)
  processing_time_limit: 0.8
